package com.printbridge.drivers

import com.printbridge.core.MonoBitmap
import com.printbridge.core.PrinterDriver
import com.printbridge.core.PrinterProfile
import com.printbridge.core.PrinterProtocol
import java.io.ByteArrayOutputStream
import java.nio.charset.CharacterCodingException
import java.nio.charset.Charset
import java.nio.charset.CodingErrorAction

class TsplDriver : PrinterDriver {
    override val protocol = PrinterProtocol.TSPL
    override fun testPage(profile: PrinterProfile): ByteArray = build(profile) {
        size(profile.paperWidthMm, profile.paperHeightMm ?: 150f)
        gap(profile.gapMm ?: 3f)
        density(8)
        speed(4)
        cls()
        text(80, 60, "PRINTBRIDGE TEST", xMul = 2, yMul = 2)
        box(20, 20, 780, 1180)
        text(80, 170, "Product:")
        text(80, 220, "PB-001", xMul = 2, yMul = 2)
        barcode(80, 340, "PB000001")
        qrcode(80, 540, "PrintBridge Test")
        text(80, 820, "DPI:")
        text(220, 820, profile.dpi.toString())
        text(80, 880, "Paper:")
        text(220, 880, "${profile.paperWidthMm.toInt()} x ${(profile.paperHeightMm ?: 150f).toInt()} mm")
        bitmap(600, 960, checkerBitmap(64, 64))
        print(1)
    }

    fun build(
        profile: PrinterProfile,
        charset: Charset = TsplText.DEFAULT_CHARSET,
        block: TsplBuilder.() -> Unit
    ): ByteArray = TsplBuilder(charset).apply(block).toByteArray()
}

class TsplBuilder(private val charset: Charset = TsplText.DEFAULT_CHARSET) {
    private val out = ByteArrayOutputStream()
    fun size(widthMm: Float, heightMm: Float) = line("SIZE ${widthMm.clean()} mm,${heightMm.clean()} mm")
    fun gap(gapMm: Float, offsetMm: Float = 0f) = line("GAP ${gapMm.clean()} mm,${offsetMm.clean()} mm")
    fun density(value: Int) = line("DENSITY ${value.coerceIn(0, 15)}")
    fun speed(value: Int) = line("SPEED ${value.coerceIn(1, 6)}")
    fun cls() = line("CLS")
    fun text(x: Int, y: Int, value: String, font: String = "0", rotation: Int = 0, xMul: Int = 1, yMul: Int = 1) =
        line("""TEXT $x,$y,"${TsplText.escape(font)}",$rotation,$xMul,$yMul,"${TsplText.escape(value)}"""")
    fun barcode(x: Int, y: Int, value: String) = line("""BARCODE $x,$y,"128",90,1,0,2,2,"${TsplText.escape(value)}"""")
    fun qrcode(x: Int, y: Int, value: String) = line("""QRCODE $x,$y,L,5,A,0,"${TsplText.escape(value)}"""")
    fun box(x1: Int, y1: Int, x2: Int, y2: Int, thickness: Int = 3) = line("BOX $x1,$y1,$x2,$y2,$thickness")
    fun bitmap(x: Int, y: Int, bitmap: MonoBitmap) {
        val bytesPerRow = (bitmap.width + 7) / 8
        line("BITMAP $x,$y,$bytesPerRow,${bitmap.height},0,")
        for (row in 0 until bitmap.height) for (col in 0 until bytesPerRow) {
            var b = 0
            for (bit in 0..7) {
                val px = col * 8 + bit
                if (px < bitmap.width && bitmap[px, row]) b = b or (0x80 shr bit)
            }
            out.write(b)
        }
        out.write('\n'.code)
    }
    fun print(copies: Int) = line("PRINT ${copies.coerceAtLeast(1)}")
    fun toByteArray(): ByteArray = out.toByteArray()

    /**
     * The command keywords are generated by the builder and are always safe; only the payload
     * is encoded here. A lossy charset would silently degrade every non-ASCII character to '?'.
     */
    private fun line(value: String) {
        out.write(TsplText.encode(value, charset))
        out.write('\n'.code)
    }
}

/**
 * Escaping and encoding rules for values embedded into TSPL command literals.
 *
 * A label value lives inside a `"..."` literal in a line-based protocol, so a raw quote or a
 * control character can terminate the literal or inject an extra TSPL command (for example a
 * `PRINT` line). [escape] protects the literal; [encode] then maps the text onto the printer's
 * single code page.
 */
internal object TsplText {
    /** Guard against runaway labels; well beyond any realistic barcode or QR payload. */
    const val MAX_LINE_CHARS: Int = 512

    /**
     * Consumer TSPL firmware is a single-code-page protocol: the printer interprets one byte as
     * one glyph. ISO-8859-1 is the default because it is byte-identical to ASCII for the command
     * keywords and to legacy output for Latin text, while still round-tripping every character up
     * to U+00FF instead of degrading it to '?'. For Cyrillic, pass [Charset] explicitly, e.g.
     * `TsplDriver().build(profile, charset = Charset.forName("windows-1251")) { ... }`.
     * The printer-side code page has to match; see docs/KNOWN_LIMITATIONS.md.
     */
    val DEFAULT_CHARSET: Charset = Charsets.ISO_8859_1

    /**
     * Makes [value] safe to place inside a TSPL `"..."` literal: every control character
     * (including newline, which would end the command line) becomes a space, and a double quote
     * is escaped. A literal built from the result can never span lines or terminate early.
     */
    fun escape(value: String): String {
        val escaped = StringBuilder(minOf(value.length, MAX_LINE_CHARS) + 8)
        for (character in value.take(MAX_LINE_CHARS)) {
            when {
                character.isISOControl() -> escaped.append(' ')
                character == '"' -> escaped.append('\\').append('"')
                else -> escaped.append(character)
            }
        }
        return String(escaped)
    }

    /**
     * Encodes a command line or literal with [charset]. Characters the code page cannot represent
     * become '?' (the JDK default replacement) rather than aborting the print job.
     */
    fun encode(value: String, charset: Charset = DEFAULT_CHARSET): ByteArray = try {
        charset.newEncoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT)
            .encode(java.nio.CharBuffer.wrap(value))
            .let { buffer -> ByteArray(buffer.remaining()).also { buffer.get(it) } }
    } catch (_: CharacterCodingException) {
        value.toByteArray(charset)
    }
}

private fun Float.clean(): String = if (this % 1f == 0f) toInt().toString() else toString()
private fun checkerBitmap(width: Int, height: Int): MonoBitmap =
    MonoBitmap(width, height, BooleanArray(width * height) { i -> ((i % width) / 8 + (i / width) / 8) % 2 == 0 })
