<#
.SYNOPSIS
    Generates a local release keystore for PrintBridge and the matching
    keystore.properties, so `assembleRelease` produces a signed APK.

.DESCRIPTION
    The generated files are git-ignored and are intended for local verification only.
    A production release key must be generated on a trusted machine, backed up
    separately, and supplied to CI through the PRINTBRIDGE_* environment variables.

.EXAMPLE
    .\tools\create-release-keystore.ps1
    .\gradlew.bat :app:assembleRelease -Pprintbridge.requireReleaseSigning=true
#>
[CmdletBinding()]
param(
    [string] $KeystorePath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'release-keystore.jks'),
    [string] $PropertiesPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'keystore.properties'),
    [string] $Alias = 'printbridge',
    [string] $DistinguishedName = 'CN=PrintBridge Release, OU=Development, O=PrintBridge, L=, ST=, C=US',
    [int] $ValidityDays = 10950,
    [switch] $Force,
    [securestring] $StorePassword
)

$ErrorActionPreference = 'Stop'

$keytool = (Get-Command keytool -ErrorAction SilentlyContinue)?.Source
if (-not $keytool) {
    $candidate = Join-Path $env:JAVA_HOME 'bin\keytool.exe'
    if (Test-Path $candidate) { $keytool = $candidate }
}
if (-not $keytool) {
    throw "keytool was not found. Add a JDK to PATH or set JAVA_HOME."
}

if ((Test-Path $KeystorePath) -and -not $Force) {
    throw "$KeystorePath already exists. Re-run with -Force to overwrite it."
}

if (-not $StorePassword) {
    $secure = Read-Host -Prompt "Keystore password (leave empty to generate a random one)" -AsSecureString
    $plain = [System.Net.NetworkCredential]::new('', $secure).Password
    if ([string]::IsNullOrWhiteSpace($plain)) {
        $bytes = New-Object byte[] 24
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $plain = ([Convert]::ToBase64String($bytes) -replace '[^A-Za-z0-9]', '').Substring(0, 20)
        Write-Host "Generated password: $plain" -ForegroundColor Yellow
        Write-Host "Store it now - it is not written anywhere else." -ForegroundColor Yellow
    }
    $StorePassword = ConvertTo-SecureString $plain -AsPlainText -Force
}

$plainPassword = [System.Net.NetworkCredential]::new('', $StorePassword).Password

& $keytool -genkeypair `
    -keystore $KeystorePath `
    -alias $Alias `
    -keyalg RSA `
    -keysize 4096 `
    -validity $ValidityDays `
    -storepass $plainPassword `
    -keypass $plainPassword `
    -dname $DistinguishedName
if ($LASTEXITCODE -ne 0) { throw "keytool failed with exit code $LASTEXITCODE" }

@"
# Generated by tools/create-release-keystore.ps1. Git-ignored - do not commit.
storeFile=$KeystorePath
storePassword=$plainPassword
keyAlias=$Alias
keyPassword=$plainPassword
"@ | Set-Content -Path $PropertiesPath -Encoding UTF8

Write-Host ""
Write-Host "Keystore:   $KeystorePath" -ForegroundColor Green
Write-Host "Properties: $PropertiesPath" -ForegroundColor Green
Write-Host ""
Write-Host "Verify signing with:" -ForegroundColor Cyan
Write-Host "  .\gradlew.bat :app:assembleRelease -Pprintbridge.requireReleaseSigning=true"
Write-Host "  .\gradlew.bat :app:signingReport"
